parameters:
  # Indique les onglets de vues à afficher
  # Possibilités: mes_fiches,consulter,rss,saisir,formulaire,listes,importer,exporter
  baz_menu: 'formulaire,consulter,saisir,listes,importer,exporter'
  # Envoi automatique de mail aux admins ?
  BAZ_ENVOI_MAIL_ADMIN: false
  # Definition d'un mail par defaut, car il y peut y avoir envoi de mail aux utilisateurs avec la constante suivante
  BAZ_ADRESSE_MAIL_ADMIN: 'noreply@%host%'
  # Choix du look du template par défaut $GLOBALS['wiki']->config['default_bazar_template']
  default_bazar_template: 'liste_accordeon.tpl.html'
  # Si un formulaire est sémantique et qu'il a un des contextes ci-dessous, nous allons chercher dans
  # /tools/bazar/presentation/templates/{cle} pour voir si une template prédéfinie existe pour ce type sémantique
  baz_semantic_types_mapping:
    https://www.w3.org/ns/activitystreams: 'activitystreams'
  # les passages de parametres query en get affectent-ils les resultats de fiches croisees avec checkboxfiche?
  global_query: 'true'
  # authorize entry creation when wiki is not opened to create page
  bazarIgnoreAcls: true

  # Valeurs liees aux flux RSS

  # Nom du site indique dans les flux rss
  BAZ_RSS_NOMSITE: '%wakka_name%'
  # Adresse Internet du site indique dans les flux rss
  BAZ_RSS_ADRESSESITE: '%base_url%'
  # Description du site indiquee dans les flux rss
  BAZ_RSS_DESCRIPTIONSITE: '%meta_description%'
  # nombre maximum d'articles présents dans le flux rss
  BAZ_NB_ENTREES_FLUX_RSS: 20
  # Logo du site indique dans les flux rss
  BAZ_RSS_LOGOSITE: 'https:#yeswiki.net/themes/margot/images/favicon.png'
  # Managing editor du site
  BAZ_RSS_MANAGINGEDITOR: 'contact@yeswiki.net (Mr YesWiki)'
  # Mail Webmaster du site
  BAZ_RSS_WEBMASTER: '%BAZ_RSS_MANAGINGEDITOR%'
  # Categorie du flux RSS
  BAZ_RSS_CATEGORIE: 'Economie Sociale et Solidaire'

  # Pour regler certaines fonctionnalites de l'application

  # Valeur par defaut d'etat de la fiche annonce apres saisie
  # 0 pour 'en attente de validation', 1 pour 'directement validee'
  BAZ_ETAT_VALIDATION: '1'
  # Type d'affichage des dates dans la liste
  # Mettre jma pour jour mois annee, ou jm, ou jmah
  BAZ_TYPE_AFFICHAGE_LISTE: 'jma'
  # Reglage de l'affichage de la liste deroulante pour la saisie des dates Mettre a true pour afficher une liste deroulante vide pour la saisie des dates
  BAZ_DATE_VIDE: false
  # Option concernant la division des resultats en pages
  BAZ_NOMBRE_RES_PAR_PAGE: 50
  # 'Jumping' ou 'Sliding' voir http:#pear.php.net/manual/fr/package.html.pager.compare.php
  BAZ_MODE_DIVISION: 'Jumping'
  # Le nombre de page a afficher avant le 'next';
  BAZ_DELTA: 12

  # Parametres pour checkbox

  # Le nombre maximum de fiches affichées par checkboxfiche sans que les champs 'Filter' et 'Cocher tout' ne soient affichés false pas de filtre
  BAZ_MAX_CHECKBOXLISTE_SANS_FILTRE: 6
  # Le nombre maximum de fiches affichées par checkboxfuche sans que le champ 'selectall' ne soit affiché ; false : récupère le paramètre BAZ_MAX_CHECKBOXLISTE_SANS_FILTRE
  BAZ_MAX_CHECKBOXENTRY_WITHOUT_SELECTALL: 7
  # type d'affichage par défaut pour checkboxfiche en mode normal
  BAZ_MAX_CHECKBOXENTRY_DISPLAY_MODE: 'list'
  # Le nombre maximum de fiches affichées par checkbox sans que le champ 'Filter' ne soit affiché ; false pas de filtre
  BAZ_MAX_CHECKBOXLIST_WITHOUT_FILTER: false
  # Le nombre maximum d'éléments affichées par radio sans que le champ 'Filter' ne soit affiché ; false pas de filtre
  BAZ_MAX_RADIO_WITHOUT_FILTER: 6
  # Le nombre maximum de fiches affichées par checkbox sans que le champ 'selectall' ne soit affiché ; false : récupère le paramètre BAZ_MAX_CHECKBOXLIST_WITHOUT_FILTER
  BAZ_MAX_CHECKBOXLIST_WITHOUT_SELECTALL: 7
  # type d'affichage par défaut pour checkbox en mode normal
  BAZ_MAX_CHECKBOXLIST_DISPLAY_MODE: 'div'
  # Hauteur d'affichage de la liste des options dans un mode Drag & Drop : null comportement par défaut (équivalent 300px), autres valeurs par exemple '450' pour 450px
  BAZ_CHECKBOX_DRAG_AND_DROP_MAX_HEIGHT: null

  # Parametres pour la carto google

  # Coordonnees du centre de la carte : France par defaut
  baz_map_center_lat: '46.22763'
  baz_map_center_lon: '2.213749'
  # prefixe des classes CSS pour les icones du marqueur
  baz_marker_icon_prefix: 'fa fa-'
  # nom court du provider de carto
  baz_provider: 'OpenStreetMap.Mapnik'
  # id du provider de carto
  baz_provider_id: ''
  # pwd du provider de carto
  baz_provider_pass: ''
  # icone du marqueur de base
  baz_marker_icon: 'bullseye'
  # couleur du marqueur de base
  baz_marker_color: 'darkred'
  # petit marqueur (par defaut : non)
  baz_small_marker: ''
  # niveau de zoom : de 1 (plus eloigne) a 15 (plus proche)
  baz_map_zoom: 5
  # taille de la carte a l'ecran: valeur de l'attribut css width de la carte
  baz_map_width: '100%'
  # taille de la carte a l'ecran : valeur de l'attribut css height de la carte
  baz_map_height: '600px'
  # afficher la navigation : true ou false
  baz_show_nav: 'true'
  # zoom a la roulette de souris : true ou false
  baz_wheel_zoom: 'false'
  # image marqueur
  baz_marker_image_file: 'tools/bazar/presentation/images/marker.png'
  # ------
  # ExternalBazarService
  baz_external_service:
    cache_time_to_check_changes: 60 # seconds
    cache_time_to_check_deletion: 86400 # seconds (1 day)
    cache_time_to_refresh_forms: 7200 # seconds (2 hours)
    time_debug: false
  # tag used to upload file at entry creation
  temp_tag_for_entry_creation: 'unknown_entry_id'
  # for edit config action
  bazar_editable_config_params:
    - 'baz_map_center_lat'
    - 'baz_map_center_lon'
    - 'baz_map_zoom'
    - 'baz_map_height'
    - 'BAZ_ADRESSE_MAIL_ADMIN'
    - 'BAZ_ENVOI_MAIL_ADMIN'
    - baz_external_service:
        - cache_time_to_check_changes
        - cache_time_to_check_deletion
        - cache_time_to_refresh_forms
    - 'bazarIgnoreAcls'

services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Bazar\Service\:
    resource: 'services/*'
  YesWiki\Bazar\Service\DateService:
    tags:
      - { name: yeswiki.event_subscriber }

  # Allows to use controllers as services
  YesWiki\Bazar\Controller\:
    resource: 'controllers/*'
