parameters:
  use_alerte: true # alerte pour quitter le mode Ã©dition
  use_hashcash: true # hashcash pour le mode edition
  use_nospam: false # antispam pour commentaires
  use_captcha: false # recaptcha
  wiki_status: 'running' # status of the wiki ('running','maintenance','hibernation')
  security_editable_config_params:
    - 'use_alerte'
    - 'use_captcha'
    - 'use_hashcash'
    - 'wiki_status'
    - archive:
        - privatePath
        - call_archive_async
        - max_nb_files
        - preupdate_backup_activated

services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Security\Service\:
    resource: 'services/*'

  # Allows to use controllers as services
  YesWiki\Security\Controller\:
    resource: 'controllers/*'
